version: "3.8"

services:
  db:
    image: postgres:13 # Specifies the PostgreSQL version (change to your desired version)
    container_name: postgres_container # Optional: Name your container
    env_file:
      - .env # Load environment variables from the .env file
    ports:
      - "5666:5432"  # Map port 5666 on the host to port 5432 in the container
    volumes:
      - pgdata:/var/lib/postgresql/data # Persist data on a named volume
    networks:
      - pg_network

volumes:
  pgdata: # Named volume for PostgreSQL data persistence

networks:
  pg_network: # Custom network for the PostgreSQL service
